### ISSUE TITLE
voicingManager.speakIgnoringEnabled should be replaced

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/utterance-queue#57] opened 2022-01-08 00:13 UTC
We need a different function to speak without using the voicing framework. We don't like the example usage in number-play. It should ideally use the UtteranceQueue.

**Comment by zepumph** [comment] 2022-04-01 20:40
Duplicate of https://github.com/phetsims/utterance-queue/issues/69

**Closed by zepumph** 2022-04-01 20:40 UTC
