### ISSUE TITLE
Voice options unavailable with MacOS 12.3 + safari

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/utterance-queue#75] opened 2022-04-04 17:18 UTC
Seen when testing https://github.com/phetsims/qa/issues/791 and also in published GFLB and John Travoltage: There are no voice options in the combobox (but Voicing works).

**Comment by jessegreenberg** [comment] 2022-04-04 22:21
I have macOS 11.6.2 and I am not able to produce this. I have voices Alex, Fred, Samantha, and Victoria.

@Nancy-Salpepi on the Mac where you found this can you please
1) Go to System Preferences -> Accessibility -> Spoken Content
2) Go to the "System Voice" pop-up menu and show which voices you have available? Mine looks like this

**Comment by Nancy-Salpepi** [comment] 2022-04-04 22:40
yeah I have a lot of voices listed there. Is there some other step I should take (maybe something changed when my computer updated to macOS 12.3?)
<img width="681" alt="Screen Shot 2022-04-04 at 6 37 59 PM" src="https://user-images.githubusercontent.com/87318828/161643400-da5ed602-b991-4861-9de1-312a050c2d61.png">

**Comment by jessegreenberg** [comment] 2022-04-04 22:45
@Nancy-Salpepi can you please trying going to "Customize..." Then find "Samantha" in the list and uncheck it. Then press "OK" to uninstall it. Then go back and re-check Samantha to download it again? Unsure if it will do anything but I think it is worth a try.

**Comment by Nancy-Salpepi** [comment] 2022-04-04 23:02
Sorry @jessegreenberg, but no change.  I even restarted my computer to make sure. Anything else you want me to try?

**Comment by zepumph** [comment] 2022-08-31 18:01
@jessegreenberg could you give a status update on this. @emily-phet, is this blocking frictions release?

**Comment by jessegreenberg** [comment] 2022-08-31 18:39
Its possible our filter for voices is removing too much. Also possible the browser just doesn't have any available voices to choose from. I was not able to reproduce on my Mac with https://github.com/phetsims/utterance-queue/issues/75#issuecomment-1088070033. We will need to work with QA to debug what is happening on that platform.

**Comment by emily-phet** [comment] 2022-09-01 19:13
@zepumph I think it would be good to do the investigation of what @jessegreenberg describes above, to determine what is the likely root of the issue, and from there decide if we want to proceed. So "blocking' for now, until we triage based on further investigation.

**Comment by zepumph** [comment] 2022-10-05 21:26
Sounds good thanks.

**Comment by zepumph** [comment] 2022-10-14 20:13
@chrisklus and I were unable to reproduce this on his safari version 15.6 (MacOS 12.6) and also when he was on MacOS 12.2. We were though able to reproduce #74. I'll have to look into that further.

**Comment by zepumph** [comment] 2022-10-19 14:53
Up next, I'd like to work with @Nancy-Salpepi because she has been the only one to reproduce it thus far.

**Comment by Nancy-Salpepi** [comment] 2022-10-19 15:23
@zepumph with macOS 12.6 and safari 16.0 voice options are now present in the combo box for published GFLB and JT, Friction 1.6.0-dev.24 and ratio and proportion 1.2.0-dev.31.

**Comment by zepumph** [comment] 2022-10-19 18:43
Great news! Given how hard it has been for @jessegreenberg, @chrisklus and I to reproduce, I feel good about closing this.

**Closed by zepumph** 2022-10-19 18:43 UTC
Labels: status:blocks-publication, dev:voicing
